#### Building Model

In [1]:
# -*- coding: utf-8 -*-
'''VGG16-places365 model for Keras
# Reference:
- [Places: A 10 million Image Database for Scene Recognition](http://places2.csail.mit.edu/PAMI_places.pdf)
'''

from __future__ import division, print_function
import os

import warnings
import numpy as np

from keras import backend as K
from keras.layers import Input
from keras.layers.core import Activation, Dense, Flatten
from keras.layers.pooling import MaxPooling2D
from keras.models import Model
from keras.layers import Conv2D
from keras.regularizers import l2
from keras.layers.core import Dropout
from keras.layers import GlobalAveragePooling2D
from keras.layers import GlobalMaxPooling2D
from keras_applications.imagenet_utils import _obtain_input_shape
from keras.engine.topology import get_source_inputs
from keras.utils.data_utils import get_file
from keras.utils import layer_utils
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input

WEIGHTS_PATH = 'https://github.com/GKalliatakis/Keras-VGG16-places365/releases/download/v1.0/vgg16-places365_weights_tf_dim_ordering_tf_kernels.h5'
WEIGHTS_PATH_NO_TOP = 'https://github.com/GKalliatakis/Keras-VGG16-places365/releases/download/v1.0/vgg16-places365_weights_tf_dim_ordering_tf_kernels_notop.h5'


def VGG16_Places365(include_top=True, weights='places',
                    input_tensor=None, input_shape=None,
                    pooling=None,
                    classes=365):
    """Instantiates the VGG16-places365 architecture.
    Optionally loads weights pre-trained
    on Places. Note that when using TensorFlow,
    for best performance you should set
    `image_data_format="channels_last"` in your Keras config
    at ~/.keras/keras.json.
    The model and the weights are compatible with both
    TensorFlow and Theano. The data format
    convention used by the model is the one
    specified in your Keras config file.
    # Arguments
        include_top: whether to include the 3 fully-connected
            layers at the top of the network.
        weights: one of `None` (random initialization),
                 'places' (pre-training on Places),
                 or the path to the weights file to be loaded.
        input_tensor: optional Keras tensor (i.e. output of `layers.Input()`)
            to use as image input for the model.
        input_shape: optional shape tuple, only to be specified
            if `include_top` is False (otherwise the input shape
            has to be `(224, 224, 3)` (with `channels_last` data format)
            or `(3, 224, 244)` (with `channels_first` data format).
            It should have exactly 3 inputs channels,
            and width and height should be no smaller than 48.
            E.g. `(200, 200, 3)` would be one valid value.
        pooling: Optional pooling mode for feature extraction
            when `include_top` is `False`.
            - `None` means that the output of the model will be
                the 4D tensor output of the
                last convolutional layer.
            - `avg` means that global average pooling
                will be applied to the output of the
                last convolutional layer, and thus
                the output of the model will be a 2D tensor.
            - `max` means that global max pooling will
                be applied.
        classes: optional number of classes to classify images
            into, only to be specified if `include_top` is True, and
            if no `weights` argument is specified.
    # Returns
        A Keras model instance.
    # Raises
        ValueError: in case of invalid argument for `weights`, or invalid input shape
        """
    if not (weights in {'places', None} or os.path.exists(weights)):
        raise ValueError('The `weights` argument should be either '
                         '`None` (random initialization), `places` '
                         '(pre-training on Places), '
                         'or the path to the weights file to be loaded.')

    if weights == 'places' and include_top and classes != 365:
        raise ValueError('If using `weights` as places with `include_top`'
                         ' as true, `classes` should be 365')


    # Determine proper input shape
    input_shape = _obtain_input_shape(input_shape,
                                      default_size=224,
                                      min_size=48,
                                      data_format=K.image_data_format(),
                                      require_flatten =include_top)

    if input_tensor is None:
        img_input = Input(shape=input_shape)
    else:
        if not K.is_keras_tensor(input_tensor):
            img_input = Input(tensor=input_tensor, shape=input_shape)
        else:
            img_input = input_tensor

    # Block 1
    x = Conv2D(filters=64, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block1_conv1')(img_input)

    x = Conv2D(filters=64, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block1_conv2')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block1_pool", padding='valid')(x)

    # Block 2
    x = Conv2D(filters=128, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block2_conv1')(x)

    x = Conv2D(filters=128, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block2_conv2')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block2_pool", padding='valid')(x)

    # Block 3
    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv1')(x)

    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv2')(x)

    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block3_pool", padding='valid')(x)

    # Block 4
    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv1')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv2')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block4_pool", padding='valid')(x)

    # Block 5
    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv1')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv2')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block5_pool", padding='valid')(x)

    if include_top:
        # Classification block
        x = Flatten(name='flatten')(x)
        x = Dense(4096, activation='relu', name='fc1')(x)
        x = Dropout(0.5, name='drop_fc1')(x)

        x = Dense(4096, activation='relu', name='fc2')(x)
        x = Dropout(0.5, name='drop_fc2')(x)
        
        x = Dense(365, activation='softmax', name="predictions")(x)
    else:
        if pooling == 'avg':
            x = GlobalAveragePooling2D()(x)
        elif pooling == 'max':
            x = GlobalMaxPooling2D()(x)

    # Ensure that the model takes into account
    # any potential predecessors of `input_tensor`.
    if input_tensor is not None:
        inputs = get_source_inputs(input_tensor)
    else:
        inputs = img_input

    # Create model.
    model = Model(inputs, x, name='vgg16-places365')

    # load weights
    if weights == 'places':
        if include_top:
            weights_path = get_file('vgg16-places365_weights_tf_dim_ordering_tf_kernels.h5',
                                    WEIGHTS_PATH,
                                    cache_subdir='models')
        else:
            weights_path = get_file('vgg16-places365_weights_tf_dim_ordering_tf_kernels_notop.h5',
                                    WEIGHTS_PATH_NO_TOP,
                                    cache_subdir='models')

        model.load_weights(weights_path)

        if K.backend() == 'theano':
            layer_utils.convert_all_kernels_in_model(model)

        if K.image_data_format() == 'channels_first':
            if include_top:
                maxpool = model.get_layer(name='block5_pool')
                shape = maxpool.output_shape[1:]
                dense = model.get_layer(name='fc1')
                layer_utils.convert_dense_weights_data_format(dense, shape, 'channels_first')

            if K.backend() == 'tensorflow':
                warnings.warn('You are using the TensorFlow backend, yet you '
                              'are using the Theano '
                              'image data format convention '
                              '(`image_data_format="channels_first"`). '
                              'For best performance, set '
                              '`image_data_format="channels_last"` in '
                              'your Keras config '
                              'at ~/.keras/keras.json.')

    elif weights is not None:
        model.load_weights(weights)

    return model



Using TensorFlow backend.


#### Create Model

In [2]:
from keras import optimizers
def create_model():
    
    model = VGG16_Places365(include_top = False, weights='places', pooling = "avg")
    
    # Freeze all layers except the last 4 layers
    for layer in model.layers[:-4]:
        layer.trainable = False

    x = model.output
#     x = Dropout(0.4)(x)
    predictions = Dense(6, activation='sigmoid')(x)
    model = Model(inputs=model.input, outputs=predictions)
    # compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizers.SGD(lr=0.001))
    
    return model

#### Load Weights with the Lowest Validation Loss

In [3]:
model = create_model()
model.load_weights("weights-improvement-112-0.90.hdf5")
print(model.summary())


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, None, None, 3)     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
______________________________

#### check if there's any corrupted file

In [10]:
from tqdm import tqdm
from PIL import Image
DATADIR = r"D:\FYP\KL_GSV"

# CATEGORIES = ["beautiful","boring","depressing","lively","safety","wealthy"]

training_data = []

def checkCorrupted():
#     for category in CATEGORIES:  
    path = DATADIR  # create path to dogs and cats
#         class_num = CATEGORIES.index(category)  # get the classification  (0 == beautiful, ... ,5 == wealthy)
    for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
#         try:
        filename = os.path.join(path,img)
#             print(filename)
        im = Image.open(filename)
        size = os.path.getsize(filename)
        if (size == 3224) :
            print(filename)

checkCorrupted()

100%|████████████████████████████████████████████████████████████████████████████| 4422/4422 [00:00<00:00, 6124.07it/s]


#### Delete record from the DF if corrupted file in the directory is deleted

In [60]:
dir = r"D:\FYP\KL_GSV"
print(len(df))
imagePath = df.loc[:,'filename'].values.tolist()

count = 0
for img in imagePath:
    path = os.path.join(dir, img)
    x = str(path).split("\\")[-1]
    if not os.path.exists(path):
        count += 1
        print(x)
        df = df[df.filename != x]
#         print(len(df))
print(count)
print(len(df))
df.to_csv(r"D:\FYP\Visualisation\test_points_KL_unique_cleaned_latest.csv")

4291
0
4291


#### Prediction

In [62]:
import cv2
import numpy as np
import os
from sklearn.metrics import classification_report, average_precision_score, precision_score
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
# classes = ["beautiful","boring","depressing","lively","safety","wealthy"]

predicted_scores = []

dir = r"D:\FYP\KL_GSV"
# imagePath = df.loc[df['Unnamed: 0'] > 20052]
imagePath = df.loc[:,'filename'].values.tolist()
print(len(imagePath))


for img in imagePath:
    try:
        path = os.path.join(dir, img)

        idx = imagePath.index(img)
        print(idx)
    #     print(imagePath.index(img))

        img = cv2.imread(path)

        y_scores = model.predict(img.reshape(1,224,224,3))
        print(path)
        print(y_scores[0])
        predicted_scores.append(y_scores[0])
    except:
        print("deleted file")

4291
0
D:\FYP\KL_GSV\ChIJYbEOt2Y4zDER1rRiQCmnKpk_0.jpg
[0.958 0.087 0.274 0.950 0.480 0.792]
1
D:\FYP\KL_GSV\ChIJf7L63GY4zDERtn4RRBJ5j8g_0.jpg
[0.824 0.093 0.899 0.969 0.008 0.261]
2
D:\FYP\KL_GSV\ChIJWZXLyGY4zDER8HrwgxBiXIM_0.jpg
[0.993 0.005 0.006 0.996 0.002 0.996]
3
D:\FYP\KL_GSV\ChIJBRqW62Y4zDER5hk-VslDi6o_0.jpg
[0.961 0.643 0.784 0.998 0.213 0.614]
4
D:\FYP\KL_GSV\ChIJVVCnx2Y4zDERuMiq6zyzIXs_0.jpg
[0.993 0.525 0.952 0.972 0.009 0.992]
5
D:\FYP\KL_GSV\ChIJ4XieRGE4zDERdtE5f_yE81g_0.jpg
[0.301 0.938 0.643 0.495 0.005 0.991]
6
D:\FYP\KL_GSV\ChIJh7QNS2E4zDER8uQZQewf8Vo_0.jpg
[0.923 0.155 0.051 0.997 0.006 0.999]
7
D:\FYP\KL_GSV\ChIJB6-MrWY4zDERQE4s69HmJfM_0.jpg
[0.649 0.735 0.949 1.000 0.221 0.954]
8
D:\FYP\KL_GSV\ChIJQ1hPOGE4zDERdkZjREI-6no_0.jpg
[0.691 0.950 0.014 0.999 0.002 0.998]
9
D:\FYP\KL_GSV\ChIJbQmI-WM4zDERBWb7oyT8gVs_0.jpg
[0.994 0.958 0.065 0.819 0.005 0.935]
10
D:\FYP\KL_GSV\ChIJI1LPF2E4zDERuiUvyloEyB4_0.jpg
[0.812 0.860 0.853 0.980 0.539 0.959]
11
D:\FYP\KL_GSV\ChIJ5Wy9W

D:\FYP\KL_GSV\ChIJC3eqyhI4zDER72zVEB2S35M_9.jpg
[0.636 0.997 0.998 0.982 0.000 0.424]
184
D:\FYP\KL_GSV\ChIJ_dGZlRI4zDERWM5nZSd05k0_9.jpg
[0.984 0.993 0.045 0.999 0.002 0.997]
185
D:\FYP\KL_GSV\ChIJC3eqyhI4zDER7mzVEB2S35M_9.jpg
[0.673 0.996 0.993 0.971 0.000 0.194]
186
D:\FYP\KL_GSV\ChIJ4Qa_rxI4zDERb7Q-H7PIiuA_9.jpg
[1.000 0.572 0.977 0.996 0.002 1.000]
187
D:\FYP\KL_GSV\ChIJq56QqhI4zDERK-E-yCMmrI0_9.jpg
[0.997 0.316 0.158 0.958 0.002 0.998]
188
D:\FYP\KL_GSV\ChIJOb1voxI4zDERSr0z_tQSb_Y_9.jpg
[0.902 0.292 0.181 0.979 0.159 0.892]
189
D:\FYP\KL_GSV\ChIJM2TTuRI4zDERhi90K_PzEoI_9.jpg
[1.000 0.877 0.983 1.000 0.000 1.000]
190
D:\FYP\KL_GSV\ChIJZYaMpxI4zDERFYSHuftt1LY_9.jpg
[0.322 0.433 0.107 0.648 0.058 0.894]
191
D:\FYP\KL_GSV\ChIJOb1voxI4zDERS70z_tQSb_Y_9.jpg
[0.910 0.873 0.715 0.987 0.001 0.947]
192
D:\FYP\KL_GSV\ChIJD8_dWQ04zDERdCyHql9rrMY_9.jpg
[0.998 0.027 0.203 1.000 0.010 0.989]
193
D:\FYP\KL_GSV\ChIJG8BNyhI4zDERV2CfCukGhEA_9.jpg
[0.994 0.998 0.325 0.992 0.001 0.997]
194
D:\FYP\KL_

D:\FYP\KL_GSV\ChIJy2-POww4zDER1-vnL80fbfE_18.jpg
[0.879 0.636 0.134 0.996 0.019 0.901]
364
D:\FYP\KL_GSV\ChIJs5Fmagw4zDERbGZVaLGjkKQ_18.jpg
[0.973 0.464 0.980 0.987 0.385 0.738]
365
D:\FYP\KL_GSV\ChIJy2-POww4zDER1uvnL80fbfE_18.jpg
[0.041 0.434 0.996 0.966 0.620 0.088]
366
D:\FYP\KL_GSV\ChIJ89gmTgw4zDERItEfNOjrmRI_18.jpg
[0.982 0.663 0.023 0.987 0.364 0.890]
367
D:\FYP\KL_GSV\ChIJCencSww4zDERhksiehDKlxs_18.jpg
[0.979 0.663 0.037 0.987 0.236 0.990]
368
D:\FYP\KL_GSV\ChIJI4WUJQw4zDER5lockJQ6kTo_18.jpg
[0.940 0.013 0.059 0.433 0.209 0.983]
369
D:\FYP\KL_GSV\ChIJHQv9PAw4zDERuuc2osZEk9A_18.jpg
[0.776 0.614 0.735 0.986 0.010 0.447]
370
D:\FYP\KL_GSV\ChIJHQv9PAw4zDERjGTx5q-dHmU_18.jpg
[0.995 0.027 0.059 0.967 0.577 0.746]
371
D:\FYP\KL_GSV\ChIJ5Sj3Qgw4zDER4vdgShCf1WA_18.jpg
[0.897 0.046 0.020 0.313 0.046 0.106]
372
D:\FYP\KL_GSV\ChIJkQo-OAw4zDERHv0dyivLxT4_18.jpg
[0.996 0.907 0.444 0.782 0.149 0.282]
373
D:\FYP\KL_GSV\ChIJGxV0Pgw4zDERDgRdasCKLvA_18.jpg
[0.973 0.116 0.633 0.984 0.156 0.835]
374

D:\FYP\KL_GSV\ChIJ8ergAWs4zDERvievaqhWXzA_26.jpg
[0.830 0.030 0.145 0.638 0.233 0.995]
544
D:\FYP\KL_GSV\ChIJzdxlWmo4zDERdrMs8DglMgw_26.jpg
[0.992 0.588 0.062 1.000 0.045 1.000]
545
D:\FYP\KL_GSV\ChIJ4-iv_Go4zDER5tZnUOVDMPE_26.jpg
[0.998 0.644 0.492 0.975 0.010 0.054]
546
D:\FYP\KL_GSV\ChIJFUxtpms4zDERodGdst0z_lY_26.jpg
[1.000 0.031 0.021 0.968 0.338 1.000]
547
D:\FYP\KL_GSV\ChIJ1-gZsms4zDER1AKLvfKsSeA_26.jpg
[0.999 0.490 0.001 1.000 0.535 0.974]
548
D:\FYP\KL_GSV\ChIJ91GGBWo4zDER2lgAew4jmDM_26.jpg
[0.891 0.844 0.085 0.993 0.005 1.000]
549
D:\FYP\KL_GSV\ChIJF1pyiWo4zDERPn2whnccV4k_26.jpg
[0.776 0.942 0.365 0.675 0.012 0.092]
550
D:\FYP\KL_GSV\ChIJK4OcXGo4zDERHWucnIkpymc_26.jpg
[0.919 0.863 0.451 1.000 0.018 0.543]
551
D:\FYP\KL_GSV\ChIJZfhhTmo4zDERQioOU5WZgPQ_26.jpg
[0.999 1.000 0.007 0.973 0.240 0.893]
552
D:\FYP\KL_GSV\ChIJgaAeAGo4zDERMmc5VoEfA1M_26.jpg
[0.997 0.364 0.168 0.937 0.008 0.376]
553
D:\FYP\KL_GSV\ChIJd-GyAGo4zDERHr3evQ_xa8g_26.jpg
[0.111 0.999 0.629 0.983 0.134 0.119]
554

D:\FYP\KL_GSV\ChIJ63khcz84zDER8vxOuES8DNY_32.jpg
[0.186 0.994 0.981 0.945 0.000 0.997]
724
D:\FYP\KL_GSV\ChIJeewQ3zs4zDEREkrL88D-XW4_32.jpg
[0.912 0.550 0.003 0.308 0.341 0.813]
725
D:\FYP\KL_GSV\ChIJFwHdojk4zDERSmJnlOAjdfw_32.jpg
[0.930 0.896 0.958 0.822 0.016 0.429]
726
D:\FYP\KL_GSV\ChIJtfQ5kjc4zDERQCiKtGF1vMo_32.jpg
[0.996 0.166 0.337 0.423 0.829 0.987]
727
D:\FYP\KL_GSV\ChIJf7_WZDk4zDERohcjoA-bCYw_32.jpg
[0.898 0.980 0.858 0.909 0.097 0.808]
728
D:\FYP\KL_GSV\ChIJlaZN1Dk4zDERJG-ySw2fchk_32.jpg
[0.943 0.207 0.923 0.987 0.080 0.998]
729
D:\FYP\KL_GSV\ChIJofCqlDk4zDER1gkewIErdTA_32.jpg
[0.972 0.017 0.163 0.981 0.287 1.000]
730
D:\FYP\KL_GSV\ChIJLYEjhzk4zDERo_J0D2JVL3I_32.jpg
[0.995 0.007 0.358 0.971 0.590 0.999]
731
D:\FYP\KL_GSV\ChIJiXrLZjk4zDERlhLJfuW3ai0_32.jpg
[0.073 0.463 0.005 0.998 0.010 1.000]
732
D:\FYP\KL_GSV\ChIJn83Wwjk4zDEROmpE3BsJUp8_32.jpg
[0.999 0.000 0.050 0.905 0.717 1.000]
733
D:\FYP\KL_GSV\ChIJJ4swmTk4zDERQG7-sBO5VOg_32.jpg
[0.958 0.986 0.837 0.742 0.065 0.461]
734

D:\FYP\KL_GSV\ChIJjTHsbS84zDERVKlALaR9vBU_46.jpg
[0.227 0.999 0.984 0.572 0.089 0.999]
904
D:\FYP\KL_GSV\ChIJCy4ciyU4zDERAEYeo7iOH3o_46.jpg
[0.994 0.995 0.063 1.000 0.003 0.996]
905
D:\FYP\KL_GSV\ChIJJ6kbpy84zDERD8pzn5tl0yo_46.jpg
[0.120 0.504 0.030 1.000 0.012 0.995]
906
D:\FYP\KL_GSV\ChIJA5W7bC84zDERrxenR65Sroo_46.jpg
[0.034 0.348 0.954 0.195 0.031 1.000]
907
D:\FYP\KL_GSV\ChIJc6S7Ty84zDERLL4IPrnMXh4_46.jpg
[0.944 0.598 0.692 1.000 0.002 1.000]
908
D:\FYP\KL_GSV\ChIJ62sB5i44zDERlMwOaftpeME_46.jpg
[0.935 0.017 0.170 0.212 0.602 0.994]
909
D:\FYP\KL_GSV\ChIJU9bDySg4zDERhtNSaK6J0pw_46.jpg
[0.958 0.131 0.957 0.987 0.000 1.000]
910
D:\FYP\KL_GSV\ChIJ5THktCg4zDERIilDlAoEdRM_46.jpg
[0.997 0.007 0.004 0.992 0.101 0.975]
911
D:\FYP\KL_GSV\ChIJbTCN2S44zDERSz4Pg7sKS6U_46.jpg
[0.991 0.002 0.129 0.127 0.680 0.999]
912
D:\FYP\KL_GSV\ChIJc_wS_S44zDERkHzlWZkM654_46.jpg
[0.998 0.052 0.321 0.983 0.650 0.995]
913
D:\FYP\KL_GSV\ChIJA4YNKC84zDERwmOsBuhEv2s_46.jpg
[1.000 0.182 0.869 0.997 0.020 1.000]
914

D:\FYP\KL_GSV\ChIJw3ZyfiQ4zDERItv2BbDeQDg_55.jpg
[0.451 0.070 0.039 0.999 0.051 0.994]
1083
D:\FYP\KL_GSV\ChIJ413BlSM4zDERFko79suY_ow_55.jpg
[0.760 0.064 0.204 0.520 0.539 0.307]
1084
D:\FYP\KL_GSV\ChIJNTV2oyM4zDERdKzbErFti54_55.jpg
[0.995 0.774 0.093 0.846 0.008 0.958]
1085
D:\FYP\KL_GSV\ChIJwxcluiM4zDERGuEsu9RNl4s_55.jpg
[0.997 0.595 0.650 0.998 0.043 0.986]
1086
D:\FYP\KL_GSV\ChIJO21KqiM4zDERmTL-la9quus_55.jpg
[0.801 0.940 0.584 0.971 0.011 0.320]
1087
D:\FYP\KL_GSV\ChIJMRyvSiM4zDERIEy3jL-SEY4_56.jpg
[0.888 0.556 0.018 0.995 0.050 0.996]
1088
D:\FYP\KL_GSV\ChIJKRLANiM4zDERXKOMRMuoEIM_56.jpg
[0.911 0.057 0.518 0.965 0.202 0.824]
1089
D:\FYP\KL_GSV\ChIJG_8-tjw4zDERaDwGYi4mKw0_56.jpg
[0.255 1.000 0.300 0.996 0.201 0.998]
1090
D:\FYP\KL_GSV\ChIJ94ICszw4zDERluGBhh89HhI_56.jpg
[0.999 0.783 0.021 0.173 0.075 0.793]
1091
D:\FYP\KL_GSV\ChIJYUCVLyM4zDERZwCkm9YjW5I_56.jpg
[0.974 0.999 0.157 1.000 0.000 0.907]
1092
D:\FYP\KL_GSV\ChIJVaooTCM4zDER-gHOE1vEWJA_56.jpg
[0.558 0.654 0.004 0.981 0.050 

D:\FYP\KL_GSV\ChIJyYgiggA4zDERhMbq4-FPhwg_64.jpg
[1.000 0.149 0.939 0.999 0.774 0.781]
1261
D:\FYP\KL_GSV\ChIJVybxkAA4zDER8fHSbIlSoMg_64.jpg
[0.679 0.317 0.473 0.994 0.007 0.963]
1262
D:\FYP\KL_GSV\ChIJ56IgLAE4zDERfHgMm5upf9M_64.jpg
[0.995 0.132 0.466 0.999 0.117 0.999]
1263
D:\FYP\KL_GSV\ChIJV2BM5QA4zDERk90_ZjnkVLQ_64.jpg
[0.873 0.089 0.017 0.851 0.032 0.918]
1264
D:\FYP\KL_GSV\ChIJYfDNev9HzDER-3LkFzh4tm8_64.jpg
[0.872 0.062 0.476 0.989 0.920 0.936]
1265
D:\FYP\KL_GSV\ChIJ32WsbwA4zDERRPJvAhqo93I_64.jpg
[0.926 0.081 0.176 0.978 0.028 0.192]
1266
D:\FYP\KL_GSV\ChIJXxTFiAA4zDERhGLTSqmYhqo_64.jpg
[0.723 0.182 0.115 0.684 0.272 0.711]
1267
D:\FYP\KL_GSV\ChIJ3fs-0As4zDER9gvDvXK5_Ck_67.jpg
[0.960 0.161 0.718 0.606 0.296 0.996]
1268
D:\FYP\KL_GSV\ChIJiVvfJgo4zDERRlWJpWfZ-ZE_67.jpg
[0.996 0.216 0.605 0.954 0.058 0.724]
1269
D:\FYP\KL_GSV\ChIJR16H9wk4zDERiFdXNYzW-aA_67.jpg
[0.995 0.268 0.984 0.326 0.111 0.978]
1270
D:\FYP\KL_GSV\ChIJxaxZgAk4zDERU93-FRgIY-w_67.jpg
[0.793 0.049 0.423 0.978 0.036 

D:\FYP\KL_GSV\ChIJpSNAaxg4zDERzCTDVUx7KhM_76.jpg
[0.935 1.000 0.956 0.994 0.000 0.026]
1439
D:\FYP\KL_GSV\ChIJz50XOBg4zDERnFkIh97KVgU_76.jpg
[0.999 0.233 0.105 0.997 0.119 0.960]
1440
D:\FYP\KL_GSV\ChIJx_LKRhg4zDERSHGz-eNFL4k_76.jpg
[1.000 0.960 0.861 0.999 0.193 0.999]
1441
D:\FYP\KL_GSV\ChIJlRTHOBg4zDER3FwnpSLltKU_76.jpg
[0.798 0.680 0.003 0.995 0.111 0.998]
1442
D:\FYP\KL_GSV\ChIJkRKBjB84zDERxhRXAJZpS5k_76.jpg
[0.376 0.993 0.638 0.321 0.004 0.213]
1443
D:\FYP\KL_GSV\ChIJXYN6dh84zDERlMF-17NR-iY_76.jpg
[0.916 0.903 0.055 0.390 0.052 0.966]
1444
D:\FYP\KL_GSV\ChIJaw6_iB84zDER0pSkNjsA7Sc_76.jpg
[1.000 0.984 0.015 1.000 0.250 0.997]
1445
D:\FYP\KL_GSV\ChIJR1WmNiA4zDERGuAeLAND7AQ_76.jpg
[0.957 0.895 0.069 0.998 0.042 0.996]
1446
D:\FYP\KL_GSV\ChIJXU2qOyA4zDERstHNShEK5bE_76.jpg
[0.927 0.637 0.479 0.995 0.074 0.356]
1447
D:\FYP\KL_GSV\ChIJW1BixvU3zDERQEkVik_mIMY_77.jpg
[0.908 0.892 0.042 0.969 0.156 0.855]
1448
D:\FYP\KL_GSV\ChIJ7yUCuPU3zDERKPOOzlHKapA_77.jpg
[0.210 0.882 0.160 0.984 0.063 

D:\FYP\KL_GSV\ChIJp9SzqQBIzDERVhYd0zDkT74_83.jpg
[0.982 0.227 0.513 0.999 0.102 0.624]
1617
D:\FYP\KL_GSV\ChIJd54lxQBIzDER2EgE172lFgg_83.jpg
[0.945 0.895 0.004 0.990 0.125 0.887]
1618
D:\FYP\KL_GSV\ChIJYwSXsQBIzDERntjLrB1aY78_83.jpg
[0.965 0.620 0.309 0.985 0.018 0.601]
1619
D:\FYP\KL_GSV\ChIJCTWswwBIzDERJd__hxcjWqo_83.jpg
[0.710 0.034 0.603 0.770 0.125 0.954]
1620
D:\FYP\KL_GSV\ChIJo1CFxgBIzDER3ex0Ove6e4g_83.jpg
[0.569 0.936 0.932 0.168 0.404 1.000]
1621
D:\FYP\KL_GSV\ChIJk9CAxwBIzDERdyAW38aGXs4_83.jpg
[0.952 0.096 0.385 0.996 0.642 0.985]
1622
D:\FYP\KL_GSV\ChIJDUmRugBIzDERalT0J9JiDyc_83.jpg
[0.998 0.098 0.204 0.960 0.567 0.026]
1623
D:\FYP\KL_GSV\ChIJg7Ub9AQ4zDERlJPFTgFo2k4_87.jpg
[0.999 0.930 0.042 0.998 0.010 0.730]
1624
D:\FYP\KL_GSV\ChIJRXCckQQ4zDERnPSrKPL2ODo_87.jpg
[0.966 0.759 0.001 0.965 0.056 0.997]
1625
D:\FYP\KL_GSV\ChIJHV1qbgM4zDER8Myh3W1sAJo_87.jpg
[0.941 0.485 0.004 0.986 0.627 0.998]
1626
D:\FYP\KL_GSV\ChIJURABcAQ4zDERDDDeDWziCgc_87.jpg
[0.979 0.866 0.175 0.999 0.005 

[0.997 0.140 0.010 0.539 0.402 0.018]
1794
D:\FYP\KL_GSV\ChIJVbcVpvg3zDER4q2fD2WaJDo_94.jpg
[0.997 0.062 0.230 0.999 0.090 0.983]
1795
D:\FYP\KL_GSV\ChIJo5GUPAI4zDERDG4QEoev9FI_94.jpg
[0.991 0.075 0.055 0.860 0.146 0.991]
1796
D:\FYP\KL_GSV\ChIJzZliPwI4zDERsHN-x6GoHwk_94.jpg
[0.289 0.390 0.650 0.868 0.179 0.782]
1797
D:\FYP\KL_GSV\ChIJT9s6lvg3zDERHDU8Qbyztl0_94.jpg
[0.815 0.968 0.742 0.995 0.020 0.617]
1798
D:\FYP\KL_GSV\ChIJ717wHgI4zDERLtCU9YoHFAs_94.jpg
[0.341 0.302 0.928 0.996 0.010 0.869]
1799
D:\FYP\KL_GSV\ChIJ7_iemBtIzDERSaMFQQ48N2k_96.jpg
[0.591 0.997 0.983 0.994 0.000 0.991]
1800
D:\FYP\KL_GSV\ChIJcXdBwBtIzDER0dBjqkLiT_w_96.jpg
[0.689 0.996 0.429 0.949 0.001 0.758]
1801
D:\FYP\KL_GSV\ChIJ3WBGnhtIzDERqxgh29uSGXU_96.jpg
[0.979 0.942 0.457 0.960 0.869 0.612]
1802
D:\FYP\KL_GSV\ChIJ01iNxBtIzDERGTzbtI3xZxQ_96.jpg
[0.159 0.013 0.024 0.798 0.002 0.917]
1803
D:\FYP\KL_GSV\ChIJiVvCxhtIzDER72x27_HYSIY_96.jpg
[0.989 0.989 0.022 1.000 0.004 0.999]
1804
D:\FYP\KL_GSV\ChIJe2z_oRtIzDER06oIOYd

D:\FYP\KL_GSV\ChIJRRlMUsI3zDERHBtXcDFobhg_106.jpg
[0.867 0.485 0.200 0.964 0.061 0.887]
1971
D:\FYP\KL_GSV\ChIJi12zXsI3zDERdMsfBjkJeQk_106.jpg
[0.492 0.011 0.015 0.968 0.262 0.976]
1972
D:\FYP\KL_GSV\ChIJ07g0RcI3zDER9Eg719z7_3w_106.jpg
[0.899 0.743 0.669 0.989 0.008 0.374]
1973
D:\FYP\KL_GSV\ChIJgSlBMMI3zDERkMdmuOGOGXI_106.jpg
[0.991 0.208 0.429 0.999 0.018 0.997]
1974
D:\FYP\KL_GSV\ChIJty8YDb83zDERMvjiOpYW9eI_106.jpg
[0.992 0.603 0.291 0.997 0.521 0.910]
1975
D:\FYP\KL_GSV\ChIJcWuQD783zDERdqcTrBRFgh0_106.jpg
[0.997 0.990 0.024 0.981 0.112 0.571]
1976
D:\FYP\KL_GSV\ChIJdStgAb83zDERSm5XQJ-3Gl8_106.jpg
[0.977 0.577 0.105 0.999 0.004 0.996]
1977
D:\FYP\KL_GSV\ChIJcWuQD783zDERLtcc2dmgfmw_106.jpg
[0.942 0.937 0.070 0.995 0.001 0.958]
1978
D:\FYP\KL_GSV\ChIJEajsCkk2zDERcrjJqp1oykA_107.jpg
[0.201 0.956 0.960 0.998 0.053 0.924]
1979
D:\FYP\KL_GSV\ChIJWSn82kk2zDERappUjVdN6Lc_107.jpg
[0.995 0.994 0.954 0.999 0.002 0.210]
1980
D:\FYP\KL_GSV\ChIJEySfkUk2zDERlkdoRT42cwg_107.jpg
[0.609 0.988 0.573 1

D:\FYP\KL_GSV\ChIJdXC4_kw2zDERslMKropOlW4_116.jpg
[0.889 0.991 0.142 0.974 0.069 0.879]
2147
D:\FYP\KL_GSV\ChIJ98p1w002zDER1i8Bdz6ncsA_116.jpg
[0.963 1.000 0.688 0.998 0.000 0.980]
2148
D:\FYP\KL_GSV\ChIJBZwdE0w2zDERJsLA7B5MQsY_116.jpg
[0.970 0.607 0.121 0.989 0.010 0.797]
2149
D:\FYP\KL_GSV\ChIJj4s3aks2zDER3n_QM1egHKU_116.jpg
[0.992 0.007 0.359 0.652 0.386 0.880]
2150
D:\FYP\KL_GSV\ChIJi19Lu002zDERYDYxc2Uodl0_117.jpg
[0.997 0.268 0.104 1.000 0.000 1.000]
2151
D:\FYP\KL_GSV\ChIJMWUbuE02zDERUp3-F8uFBQg_117.jpg
[0.977 0.997 0.042 1.000 0.024 1.000]
2152
D:\FYP\KL_GSV\ChIJd9X2kk02zDERcNdYVFxqmH4_117.jpg
[0.983 0.355 0.706 0.029 0.046 0.992]
2153
D:\FYP\KL_GSV\ChIJNfDBT8k3zDERBGySQxZTZgA_117.jpg
[0.016 0.319 0.970 0.997 0.052 0.914]
2154
D:\FYP\KL_GSV\ChIJRzK_38s3zDERRkbZ-2qNbiE_117.jpg
[1.000 0.022 0.089 0.974 0.996 0.616]
2155
D:\FYP\KL_GSV\ChIJ-Wxv7ss3zDERnsJKVI1GBCY_117.jpg
[0.964 0.011 0.998 0.896 0.267 0.995]
2156
D:\FYP\KL_GSV\ChIJzYTcesk3zDERKh8QdI5a1Uk_117.jpg
[0.936 0.907 0.961 0

D:\FYP\KL_GSV\ChIJx0LITUk2zDERDe_J9miGV4k_123.jpg
[0.999 0.077 0.004 0.904 0.790 1.000]
2323
D:\FYP\KL_GSV\ChIJ51RXsk42zDER7LC_YurBUvk_123.jpg
[0.986 0.939 0.478 0.977 0.029 0.953]
2324
D:\FYP\KL_GSV\ChIJY5f46Ew2zDERGkK87Fq3KOw_123.jpg
[1.000 0.348 0.018 1.000 0.042 0.998]
2325
D:\FYP\KL_GSV\ChIJfUAIkEw2zDERKV-JU-cz5x8_123.jpg
[0.994 0.001 0.680 0.999 0.048 1.000]
2326
D:\FYP\KL_GSV\ChIJ0_bT9Ew2zDERPbP5AqoVeAE_123.jpg
[0.999 0.979 0.099 1.000 0.067 0.999]
2327
D:\FYP\KL_GSV\ChIJ8e-Rx0w2zDERbjIT9LRPWHY_123.jpg
[0.759 0.013 0.515 0.989 0.499 0.964]
2328
D:\FYP\KL_GSV\ChIJSWK3l0w2zDERBnqvyTptUTc_123.jpg
[0.996 0.016 0.009 0.998 0.296 1.000]
2329
D:\FYP\KL_GSV\ChIJ8e-Rx0w2zDERunqmHlBw6nk_123.jpg
[0.997 0.318 0.305 0.915 0.198 0.959]
2330
D:\FYP\KL_GSV\ChIJwzgG9Ew2zDERQOtnAfScGyQ_123.jpg
[0.998 0.030 0.055 0.967 0.527 0.837]
2331
D:\FYP\KL_GSV\ChIJ4X-GxUw2zDERMnSiJOUD9Qw_123.jpg
[0.928 0.104 0.185 0.989 0.358 0.953]
2332
D:\FYP\KL_GSV\ChIJ42YOhkw2zDEREWnxxUvnsu4_123.jpg
[0.996 0.005 0.039 0

D:\FYP\KL_GSV\ChIJubr6x0c2zDERWrR407AL8tg_134.jpg
[0.522 0.165 0.799 0.989 0.008 0.980]
2499
D:\FYP\KL_GSV\ChIJIbsL6Ec2zDERSCRnZFuxG8E_134.jpg
[0.915 0.947 0.547 0.216 0.182 0.839]
2500
D:\FYP\KL_GSV\ChIJi9IQjkc2zDERbqMwUtMXvG8_134.jpg
[0.268 0.368 0.005 0.840 0.067 0.998]
2501
D:\FYP\KL_GSV\ChIJr7Dd1Ec2zDERfiNBs_QpvN4_134.jpg
[0.975 0.129 0.078 0.998 0.128 0.809]
2502
D:\FYP\KL_GSV\ChIJ9Sxnu0c2zDERCFsK_-UJeOY_134.jpg
[0.954 0.808 0.032 0.995 0.049 0.865]
2503
D:\FYP\KL_GSV\ChIJ9Sxnu0c2zDERsOePtEfbPCk_134.jpg
[0.997 0.045 0.005 0.992 0.081 0.908]
2504
D:\FYP\KL_GSV\ChIJQ8b-qkc2zDERzgLKMXBMkO0_134.jpg
[0.999 0.061 0.002 0.991 0.071 0.063]
2505
D:\FYP\KL_GSV\ChIJtzaP7Ec2zDER4otzdNEkeiQ_134.jpg
[0.997 0.935 0.409 0.953 0.618 0.845]
2506
D:\FYP\KL_GSV\ChIJRajWEUc2zDER0NCwfsR_0TM_134.jpg
[0.999 0.010 0.056 0.998 0.057 0.999]
2507
D:\FYP\KL_GSV\ChIJpZCq1hE2zDERcqv_mey1ZJI_135.jpg
[0.635 0.552 0.618 0.789 0.063 0.815]
2508
D:\FYP\KL_GSV\ChIJnVDpKxA2zDERZjwnJnEQYsg_135.jpg
[0.939 0.992 0.828 0

D:\FYP\KL_GSV\ChIJOUI7IRY2zDERTpf7IH0Ef9U_143.jpg
[0.974 0.056 0.177 0.971 0.040 0.999]
2675
D:\FYP\KL_GSV\ChIJBT0hez02zDERt5CJ8elFALQ_143.jpg
[0.970 0.006 0.012 0.263 0.108 0.068]
2676
D:\FYP\KL_GSV\ChIJk-WQbT02zDER4wIHuJwHNaM_143.jpg
[0.956 0.604 0.415 0.993 0.019 0.999]
2677
D:\FYP\KL_GSV\ChIJGfxuPz02zDERdZbtfaLJ86c_143.jpg
[0.993 0.998 0.027 0.998 0.000 0.289]
2678
D:\FYP\KL_GSV\ChIJsRDZhT02zDERcsAR59qhD2s_143.jpg
[0.999 0.971 0.056 0.999 0.000 0.999]
2679
D:\FYP\KL_GSV\ChIJZaaMHxY2zDER6PWjWbvZA0o_143.jpg
[0.782 0.044 0.991 0.962 0.002 0.426]
2680
D:\FYP\KL_GSV\ChIJ647adj02zDERqy01eQ66wEo_143.jpg
[0.992 0.914 0.995 0.980 0.004 0.983]
2681
D:\FYP\KL_GSV\ChIJxRQajD02zDER5uc6RhQrQNg_143.jpg
[0.995 0.906 0.020 0.996 0.017 0.999]
2682
D:\FYP\KL_GSV\ChIJNR6knj02zDERr718LEMM8fU_143.jpg
[0.610 0.009 0.143 0.932 0.321 0.495]
2683
D:\FYP\KL_GSV\ChIJE_Hdgj02zDERYPNSBZVbGME_143.jpg
[0.590 0.167 0.764 0.714 0.024 0.133]
2684
D:\FYP\KL_GSV\ChIJ4zu-FD02zDERNNfSl4Hifw8_143.jpg
[0.855 0.998 0.913 1

D:\FYP\KL_GSV\ChIJFUK4PyM2zDERW9BHyahVGl0_153.jpg
[0.926 0.140 0.008 0.895 0.134 0.996]
2851
D:\FYP\KL_GSV\ChIJUdbtpiY2zDERDyeVfCRZj1I_153.jpg
[0.948 0.782 0.427 0.856 0.000 0.999]
2852
D:\FYP\KL_GSV\ChIJwUUzDSM2zDERfmAoQMsOmqU_153.jpg
[0.051 0.196 0.960 0.305 0.189 0.553]
2853
D:\FYP\KL_GSV\ChIJZavJBiQ2zDER71B4HVRWv84_153.jpg
[0.984 0.958 0.735 0.659 0.131 0.985]
2854
D:\FYP\KL_GSV\ChIJyYk54CM2zDERERf_mVmGZok_153.jpg
[0.956 0.228 0.046 0.999 0.039 1.000]
2855
D:\FYP\KL_GSV\ChIJpdQHPSQ2zDERyGSWtpuzwFU_153.jpg
[0.994 0.468 0.650 0.999 0.001 1.000]
2856
D:\FYP\KL_GSV\ChIJKSurfyM2zDERqGAf69BB_Eo_153.jpg
[0.999 0.950 0.002 0.998 0.053 0.999]
2857
D:\FYP\KL_GSV\ChIJ57xotyI2zDERqW-K9cYc42Y_153.jpg
[0.048 0.888 0.781 0.176 0.002 0.314]
2858
D:\FYP\KL_GSV\ChIJ41YkwiI2zDER3MVaopudEnE_153.jpg
[0.982 0.999 0.497 0.781 0.217 0.103]
2859
D:\FYP\KL_GSV\ChIJcQd8uCQ2zDERdPbBLgSkEbA_147.jpg
[0.999 0.470 0.017 0.866 0.257 0.930]
2860
D:\FYP\KL_GSV\ChIJQWM_jiQ2zDERUM-y5uFSHFc_147.jpg
[0.983 0.240 1.000 0

D:\FYP\KL_GSV\ChIJu0ribc5JzDERVV7q0vJQirs_161.jpg
[1.000 0.011 0.184 1.000 0.005 1.000]
3027
D:\FYP\KL_GSV\ChIJIaztvM43zDERFMzoZaAz9SM_167.jpg
[1.000 0.998 0.489 0.998 0.000 0.996]
3028
D:\FYP\KL_GSV\ChIJmZINfMw3zDERIoxo14pZ2bE_167.jpg
[0.893 0.007 0.004 0.817 0.004 0.897]
3029
D:\FYP\KL_GSV\ChIJ83h8-Ms3zDERYr8b4MOMmQs_167.jpg
[0.920 0.960 0.627 0.448 0.916 0.864]
3030
D:\FYP\KL_GSV\ChIJt4pEYcw3zDERZOBbIHIzMl0_167.jpg
[0.859 0.004 0.163 0.967 0.592 0.360]
3031
D:\FYP\KL_GSV\ChIJ5-e9O8w3zDERvUPzFTpMxNw_167.jpg
[0.891 0.995 0.999 0.998 0.015 0.921]
3032
D:\FYP\KL_GSV\ChIJR7NpK9BJzDERTleZhe2DfHM_167.jpg
[0.999 0.993 0.990 1.000 0.005 1.000]
3033
D:\FYP\KL_GSV\ChIJNVGUNNBJzDER--lPiwTFxxI_167.jpg
[0.661 0.142 0.990 0.928 0.152 0.989]
3034
D:\FYP\KL_GSV\ChIJ24I7SNBJzDERQtSiDhzazjg_167.jpg
[0.292 0.999 0.087 1.000 0.000 1.000]
3035
D:\FYP\KL_GSV\ChIJ8SRk-dBJzDERFUlUByCTcmM_167.jpg
[0.999 0.997 0.870 0.999 0.005 1.000]
3036
D:\FYP\KL_GSV\ChIJ4eEBPNBJzDER9tuWlgi9_qs_167.jpg
[0.999 0.993 0.873 0

D:\FYP\KL_GSV\ChIJiQJ0gdc3zDERbXPzY-oNoVM_175.jpg
[0.934 0.030 0.393 0.042 0.004 0.965]
3203
D:\FYP\KL_GSV\ChIJHW3stNs3zDERFuucVQ6vA0E_175.jpg
[0.989 0.034 0.554 0.962 0.440 0.998]
3204
D:\FYP\KL_GSV\ChIJyQL_qNs3zDERYLaqSGjxc9s_175.jpg
[0.995 0.015 0.009 0.989 0.036 0.641]
3205
D:\FYP\KL_GSV\ChIJCVWyPdo3zDERWWxPES6Bs4o_175.jpg
[0.996 0.189 0.139 0.996 0.005 1.000]
3206
D:\FYP\KL_GSV\ChIJ1_OzXCs2zDERs4MLrDr8bdw_175.jpg
[1.000 0.998 0.852 1.000 0.000 1.000]
3207
D:\FYP\KL_GSV\ChIJn8eYaCs2zDERKEqCSr1KPgs_175.jpg
[0.997 0.955 1.000 1.000 0.006 1.000]
3208
D:\FYP\KL_GSV\ChIJq6-j7ys2zDERXkpkZXvot1c_175.jpg
[0.992 0.214 0.099 1.000 0.002 1.000]
3209
D:\FYP\KL_GSV\ChIJk9GkcSw2zDERAAsAKq6HKeI_175.jpg
[1.000 0.177 0.054 1.000 0.002 1.000]
3210
D:\FYP\KL_GSV\ChIJ3USPQCs2zDERlW1u4wFuLfg_175.jpg
[0.986 0.260 0.237 0.996 0.006 1.000]
3211
D:\FYP\KL_GSV\ChIJJ0ZKiis2zDERn0_2QyKxJPw_175.jpg
[0.968 1.000 0.460 0.001 0.039 0.938]
3212
D:\FYP\KL_GSV\ChIJl2Ug8iw2zDERDvo4kmjlMQM_175.jpg
[0.211 0.937 0.987 0

D:\FYP\KL_GSV\ChIJP0Kb2is2zDERiPY3uKgCsGc_183.jpg
[0.989 0.008 0.538 0.866 0.125 0.952]
3379
D:\FYP\KL_GSV\ChIJQeXa-Sk2zDERqJkAGmWeBZI_183.jpg
[0.026 0.084 1.000 0.080 0.000 1.000]
3380
D:\FYP\KL_GSV\ChIJ18ZYjtdJzDERoJ0B-wrrTuo_184.jpg
[0.921 0.834 0.669 0.999 0.001 0.917]
3381
D:\FYP\KL_GSV\ChIJvZY4-tdJzDERwXHF75K9hi8_184.jpg
[0.998 0.585 0.324 0.995 0.203 0.997]
3382
D:\FYP\KL_GSV\ChIJq4q5r9dJzDERBGmO23We_hM_184.jpg
[0.357 0.994 0.998 0.999 0.000 0.012]
3383
D:\FYP\KL_GSV\ChIJlbkmWNZJzDERIGNwVV00HYE_184.jpg
[0.946 0.995 0.036 0.995 0.001 0.987]
3384
D:\FYP\KL_GSV\ChIJfxX2u9dJzDERpjQDqRXW_Qc_184.jpg
[1.000 0.907 0.994 1.000 0.001 1.000]
3385
D:\FYP\KL_GSV\ChIJ2wLvNdZJzDERYcUPh0TiDGo_184.jpg
[0.097 0.873 0.817 0.327 0.040 1.000]
3386
D:\FYP\KL_GSV\ChIJcyMvWNZJzDERGdvBOKKUGLs_184.jpg
[0.028 0.827 0.008 0.332 0.008 0.998]
3387
D:\FYP\KL_GSV\ChIJFwVOVdZJzDER2bxjfYFAVLI_184.jpg
[0.821 0.999 0.377 1.000 0.023 0.999]
3388
D:\FYP\KL_GSV\ChIJuRQW-tdJzDERdny1-7u0NS8_184.jpg
[0.916 0.110 0.073 0

D:\FYP\KL_GSV\ChIJhalzUi1IzDERv6zBtW-sWaY_192.jpg
[0.918 1.000 0.946 1.000 0.001 0.016]
3555
D:\FYP\KL_GSV\ChIJNatNSyxIzDERkqYeboYR4R8_192.jpg
[0.998 0.967 0.794 1.000 0.003 1.000]
3556
D:\FYP\KL_GSV\ChIJQU7G1S1IzDERbvz_0E8mZNs_192.jpg
[0.111 0.184 1.000 0.971 0.000 1.000]
3557
D:\FYP\KL_GSV\ChIJm2v7JC1IzDER4UQneTNIyUE_192.jpg
[0.688 0.375 0.108 0.997 0.014 1.000]
3558
D:\FYP\KL_GSV\ChIJMcYddC1IzDERoeTSFjU0rl8_192.jpg
[0.998 0.129 0.769 0.999 0.014 1.000]
3559
D:\FYP\KL_GSV\ChIJM136QS1IzDERcFmJfCDFTnY_192.jpg
[0.988 1.000 0.945 1.000 0.009 0.207]
3560
D:\FYP\KL_GSV\ChIJe9bBVc1JzDERnx0I2WKXeTA_192.jpg
[0.999 0.007 0.010 0.995 0.058 1.000]
3561
D:\FYP\KL_GSV\ChIJ8-DeXC1IzDERpLV12p9hRMU_192.jpg
[1.000 0.101 0.576 1.000 0.039 0.990]
3562
D:\FYP\KL_GSV\ChIJMysxty1IzDERp2dTc20vQ7A_192.jpg
[1.000 0.998 0.951 0.998 0.003 1.000]
3563
D:\FYP\KL_GSV\ChIJ9bo-ri1IzDER11Wrzolky6o_192.jpg
[0.925 0.999 0.998 0.999 0.000 0.998]
3564
D:\FYP\KL_GSV\ChIJN0uYKSg2zDERYfvBdXXCdkE_192.jpg
[0.999 0.872 0.036 1

D:\FYP\KL_GSV\ChIJRbpAvyBIzDERZuP2muxAAzU_201.jpg
[0.641 0.987 0.978 1.000 0.018 0.892]
3731
D:\FYP\KL_GSV\ChIJ3fNnxd43zDERnkA2m_9Z9yU_201.jpg
[0.993 0.002 0.053 0.989 0.075 0.897]
3732
D:\FYP\KL_GSV\ChIJUaWjOt83zDER3joewhCGo7o_201.jpg
[0.997 0.970 0.013 0.999 0.021 0.894]
3733
D:\FYP\KL_GSV\ChIJ80nbYjJIzDERVomS4UxPBeA_201.jpg
[0.988 0.338 0.993 0.998 0.000 1.000]
3734
D:\FYP\KL_GSV\ChIJZ24rhjJIzDERBm9Ob1Np250_201.jpg
[0.987 0.998 0.994 0.992 0.005 0.519]
3735
D:\FYP\KL_GSV\ChIJ3U24By5IzDER8zz2NZokDvA_201.jpg
[0.935 0.014 0.156 1.000 0.001 1.000]
3736
D:\FYP\KL_GSV\ChIJU_yZfzJIzDERnnWOXB4r5os_201.jpg
[0.313 0.300 0.966 0.815 0.035 0.606]
3737
D:\FYP\KL_GSV\ChIJiZfxjds3zDER4XaDkQ_X2ng_202.jpg
[0.131 0.998 0.990 0.927 0.000 0.102]
3738
D:\FYP\KL_GSV\ChIJFReP7Ns3zDERIbaqahzkmh4_202.jpg
[0.985 0.310 0.052 0.471 0.001 0.592]
3739
D:\FYP\KL_GSV\ChIJ15gcC9w3zDERIWB3VlPE6vM_202.jpg
[0.992 0.001 0.606 0.999 0.257 1.000]
3740
D:\FYP\KL_GSV\ChIJheavnNs3zDERfj_YxBrOKSQ_202.jpg
[0.926 0.044 0.000 0

D:\FYP\KL_GSV\ChIJmXooKb43zDER6B12cI5PMDg_98.jpg
[0.971 0.277 0.001 0.991 0.643 0.633]
3907
D:\FYP\KL_GSV\ChIJ28tcLb43zDERNq-9oj9oIp4_98.jpg
[0.998 0.866 0.009 0.963 0.008 0.904]
3908
D:\FYP\KL_GSV\ChIJ9RfxS743zDER6D7RjGZlqGE_98.jpg
[0.989 0.300 0.005 0.997 0.131 0.356]
3909
D:\FYP\KL_GSV\ChIJQ5oTRr43zDERCuHBsamZRPI_98.jpg
[0.631 0.051 0.013 0.467 0.309 0.140]
3910
D:\FYP\KL_GSV\ChIJVe5OSr43zDERtjss9DJnV28_98.jpg
[0.117 0.017 0.223 0.979 0.119 0.144]
3911
D:\FYP\KL_GSV\ChIJHbkZAr43zDERm4ZvZu4jVlA_98.jpg
[1.000 0.033 0.031 0.990 0.113 0.950]
3912
D:\FYP\KL_GSV\ChIJXS7Ix903zDERJt9ScoC6Wq8_98.jpg
[1.000 0.884 0.002 0.999 0.003 0.999]
3913
D:\FYP\KL_GSV\ChIJXS4yvd03zDERXBTjrAoJMdA_98.jpg
[0.785 0.303 0.769 0.991 0.882 0.149]
3914
D:\FYP\KL_GSV\ChIJczjnst03zDERrXy9Bi9ayPA_98.jpg
[0.999 0.275 0.062 0.833 0.776 0.017]
3915
D:\FYP\KL_GSV\ChIJO1ePjec3zDERtlmDC4CWNhk_98.jpg
[0.986 0.940 0.425 0.996 0.012 0.686]
3916
D:\FYP\KL_GSV\ChIJuxwOY903zDERyqR2HE2qvBQ_98.jpg
[0.981 0.136 0.212 0.814 0.114 

D:\FYP\KL_GSV\ChIJVZFaqTxIzDERggEEahEw5SI_219.jpg
[0.987 0.845 0.999 0.898 0.055 0.992]
4083
D:\FYP\KL_GSV\ChIJ3xa1RCVIzDERXuk3ej3vxjY_219.jpg
[0.142 0.745 0.977 0.940 0.026 0.682]
4084
D:\FYP\KL_GSV\ChIJJW8zzCRIzDERqnFcVyf57Fg_219.jpg
[0.773 1.000 0.990 0.990 0.019 0.983]
4085
D:\FYP\KL_GSV\ChIJeVkb9h44zDERUJt7_l3ySws_220.jpg
[0.818 0.621 0.287 0.605 0.005 0.986]
4086
D:\FYP\KL_GSV\ChIJ8dJl6R44zDER4B6GmUKjAho_220.jpg
[0.482 0.523 0.219 0.280 0.407 0.967]
4087
D:\FYP\KL_GSV\ChIJ-25RFh44zDERrqeXTe4LosQ_220.jpg
[0.993 0.583 0.112 0.916 0.185 0.966]
4088
D:\FYP\KL_GSV\ChIJD9RTQx44zDEREqNIMNV1Z5Q_220.jpg
[0.971 0.969 0.816 0.482 0.066 0.998]
4089
D:\FYP\KL_GSV\ChIJF_-EYh44zDERvRU_A-WsIjs_220.jpg
[0.318 0.980 0.999 0.092 0.001 0.071]
4090
D:\FYP\KL_GSV\ChIJk2uQlh44zDER0ELSkDRZWHw_220.jpg
[0.998 0.935 0.152 0.974 0.041 0.943]
4091
D:\FYP\KL_GSV\ChIJUS-hZx44zDERNLE0ygKxUNQ_220.jpg
[0.992 0.996 0.031 0.988 0.011 0.966]
4092
D:\FYP\KL_GSV\ChIJB4sz7h44zDERVBEDsoHdgnQ_220.jpg
[0.980 0.155 0.946 0

[0.142 0.086 0.015 0.448 0.600 0.999]
4259
D:\FYP\KL_GSV\ChIJrVmPQho4zDERO7xaQ8QpPbo_65.jpg
[0.829 0.050 0.978 0.032 0.007 0.100]
4260
D:\FYP\KL_GSV\ChIJcRiU4ho4zDERgHTUISRKxOA_65.jpg
[0.600 0.972 0.879 1.000 0.000 1.000]
4261
D:\FYP\KL_GSV\ChIJJRhvCxA4zDERHZrPjPeNFa8_65.jpg
[0.701 0.896 0.943 0.999 0.000 0.932]
4262
D:\FYP\KL_GSV\ChIJFcdtERo4zDERjMhD1irmFOg_65.jpg
[0.960 0.610 0.861 0.657 0.002 0.141]
4263
D:\FYP\KL_GSV\ChIJ_7FTUxc4zDERhto9vlCKZJ8_65.jpg
[0.945 0.975 0.897 0.990 0.480 0.999]
4264
D:\FYP\KL_GSV\ChIJ1XCGTgU4zDERxa8J_m9EtWA_65.jpg
[0.971 0.983 0.261 0.964 0.099 0.995]
4265
D:\FYP\KL_GSV\ChIJz7L8rRo4zDERSI-mSjy-Ftc_65.jpg
[0.936 0.996 0.214 0.996 0.000 0.668]
4266
D:\FYP\KL_GSV\ChIJ24d1ohs4zDERaqjin5tcq78_65.jpg
[0.923 0.998 0.843 0.009 0.000 0.974]
4267
D:\FYP\KL_GSV\ChIJ_ToYYxA4zDER5pEnziNjc7k_65.jpg
[0.901 0.987 0.209 0.998 0.005 0.999]
4268
D:\FYP\KL_GSV\ChIJOQ0RrBA4zDERtFgQiG0dQyQ_65.jpg
[0.898 0.787 0.105 0.985 0.037 0.999]
4269
D:\FYP\KL_GSV\ChIJj9wepBA4zDERuKE7M3I

In [67]:
df = df.reset_index(drop=True)

#### Append predicted result to df

In [68]:
# append predicted result to df

labels = pd.DataFrame(predicted_scores)
labels.columns = ["beautiful","boring","depressing","lively","safety","wealthy"]
labelled_df = df.join(labels) 
labelled_df
labelled_df.to_csv(r"D:\FYP\Visualisation\labelled_KL_latest_cleaned_latest.csv")

In [69]:
labelled_df

Unnamed: 0                            filename  latitude   longitude  \
0              0   ChIJYbEOt2Y4zDER1rRiQCmnKpk_0.jpg  3.224395  101.725032   
1              1   ChIJf7L63GY4zDERtn4RRBJ5j8g_0.jpg  3.223890  101.726111   
2              2   ChIJWZXLyGY4zDER8HrwgxBiXIM_0.jpg  3.224468  101.725888   
3              3   ChIJBRqW62Y4zDER5hk-VslDi6o_0.jpg  3.223750  101.725436   
4              4   ChIJVVCnx2Y4zDERuMiq6zyzIXs_0.jpg  3.223907  101.725502   
5              5   ChIJ4XieRGE4zDERdtE5f_yE81g_0.jpg  3.225625  101.724582   
6              6   ChIJh7QNS2E4zDER8uQZQewf8Vo_0.jpg  3.225141  101.725059   
7              7   ChIJB6-MrWY4zDERQE4s69HmJfM_0.jpg  3.224915  101.724679   
8              8   ChIJQ1hPOGE4zDERdkZjREI-6no_0.jpg  3.226873  101.724550   
9              9   ChIJbQmI-WM4zDERBWb7oyT8gVs_0.jpg  3.225418  101.723208   
10            10   ChIJI1LPF2E4zDERuiUvyloEyB4_0.jpg  3.226372  101.725990   
11            11   ChIJ5Wy9WWE4zDERHiXuRq-3tzk_0.jpg  3.224917  101.723953   
12            12   ChIJr22qvGY4zDERVmtv9_WrblM_0.jpg  3.224347  101.724971   
13            13   ChIJySHpMmE4zDERBKbQGppGIFA_0.jpg  3.225106  101.726125   
14            14   ChIJYxk9JWE4zDER1vQak0muedU_0.jpg  3.225725  101.726189   
15            15   ChIJaaCnyWY4zDER3--cE7LVQoQ_0.jpg  3.224575  101.725489   
16            16   ChIJ6d-uSGE4zDERiJQrjg3Rt7c_0.jpg  3.225726  101.725037   
17            17   ChIJF5RmB2Q4zDERAghoqsCr3Os_0.jpg  3.224931  101.723424   
18            18   ChIJOWOz72M4zDERQA-lvVL7sBQ_0.jpg  3.225681  101.722813   
19            19   ChIJOxmQWGQ4zDERtHSAEFClEZU_1.jpg  3.223542  101.721679   
20            20   ChIJOxmQWGQ4zDERtXSAEFClEZU_1.jpg  3.223742  101.721871   
21            21   ChIJazaVEmQ4zDEROvQONX1j2Cs_1.jpg  3.224356  101.722512   
22            22   ChIJrVg8Z2Q4zDERTF7FzpoVzJE_1.jpg  3.224140  101.721515   
23            23   ChIJD0778WQ4zDERc_DFuwKf14M_1.jpg  3.223501  101.720407   
24            24   ChIJmcKlDWQ4zDER4ujI5_pBt8Y_1.jpg  3.224424  101.722583   
25            25   ChIJgZb1XWQ4zDER9lf7E09nrAY_1.jpg  3.223930  101.721768   
26            26   ChIJ04As9GQ4zDERK1J7PS9FCJw_1.jpg  3.223507  101.720718   
27            27   ChIJQ7vebGQ4zDERAj87ipMyb5I_1.jpg  3.224149  101.722315   
28            28   ChIJn7xdPGQ4zDERUNAfCKQXuug_1.jpg  3.223454  101.722813   
29            29   ChIJiTTSDWQ4zDERAEyql_-OZqQ_1.jpg  3.224436  101.722757   
...          ...                                 ...       ...         ...   
4261        4414  ChIJJRhvCxA4zDERHZrPjPeNFa8_65.jpg  3.200694  101.719522   
4262        4415  ChIJFcdtERo4zDERjMhD1irmFOg_65.jpg  3.199639  101.722470   
4263        4416  ChIJ_7FTUxc4zDERhto9vlCKZJ8_65.jpg  3.201018  101.723710   
4264        4417  ChIJ1XCGTgU4zDERxa8J_m9EtWA_65.jpg  3.199665  101.717827   
4265        4418  ChIJz7L8rRo4zDERSI-mSjy-Ftc_65.jpg  3.199849  101.718576   
4266        4420  ChIJ24d1ohs4zDERaqjin5tcq78_65.jpg  3.197098  101.721809   
4267        4421  ChIJ_ToYYxA4zDER5pEnziNjc7k_65.jpg  3.201216  101.721060   
4268        4422  ChIJOQ0RrBA4zDERtFgQiG0dQyQ_65.jpg  3.200583  101.723743   
4269        4423  ChIJj9wepBA4zDERuKE7M3IBXiM_65.jpg  3.200751  101.722961   
4270        4424  ChIJ129NJBo4zDERNtIpmUBB1Hc_65.jpg  3.198268  101.722860   
4271        4425  ChIJixiFsj84zDER96DIVMq3RJI_29.jpg  3.207850  101.731705   
4272        4426  ChIJE9qT3T44zDERksmm9nApYm0_29.jpg  3.206993  101.733989   
4273        4427  ChIJcVyJNT44zDER0vuyysSMP_w_29.jpg  3.207502  101.730998   
4274        4428  ChIJyyelYj44zDERk4LxKyqpVUs_29.jpg  3.205783  101.732383   
4275        4429  ChIJ9W9Haj44zDERcDs67OuijR8_29.jpg  3.206342  101.731297   
4276        4430  ChIJj5AFBT84zDERcD_YG5njeRE_29.jpg  3.208196  101.732975   
4277        4431  ChIJXcFFCTw4zDER_hzr83I4CHk_29.jpg  3.204263  101.735041   
4278        4432  ChIJJ4dSOT44zDER0IkfuZqc7TY_29.jpg  3.206627  101.730909   
4279        4433  ChIJIcWLuD44zDERhPnWRteQjTI_29.jpg  3.206277  101.734337   
4280        4434  ChIJaWgtnD